### ISSUE TITLE
请求提交新站

### ISSUE THREAD

**Issue by zhushen12580** [iAmCorey/devtoolset#1]
name：LLM GPU Helper
url：https://llmgpuhelper.com
标签：LLM、GPU、Agent、RAG
brief：大模型资源平台：提供GPU内存计算、个性化模型推荐和全面知识库，助您精准选择和高效应用AI模型。
description：
探索人工智能的无限可能 - 让您的大语言模型项目如虎添翼

欢迎来到您的AI助手中心,这里是您优化大语言模型(LLM)性能的一站式平台。我们精心打造的工具和资源将帮助您突破AI极限,实现更智能、更高效的项目部署。

我们的GPU内存计算器为您提供精确估算,确保资源得到最佳分配,避免浪费。个性化的模型推荐功能则根据您的硬件配置、项目需求和性能目标,为您量身定制最佳LLM选择。

但这仅仅是开始。我们不断更新的知识库汇集了LLM优化技巧、最佳实践和行业洞察,让您始终站在AI创新的前沿。无论您是刚刚起步还是经验丰富的开发者,这里都有助您登峰造极的宝贵资源。

准备好释放AI的全部潜力了吗?立即加入我们,让您的LLM项目腾飞!

**Comment by iAmCorey** [comment]
> name：LLM GPU Helper url：https://llmgpuhelper.com 标签：LLM、GPU、Agent、RAG brief：大模型资源平台：提供GPU内存计算、个性化模型推荐和全面知识库，助您精准选择和高效应用AI模型。 description： 探索人工智能的无限可能 - 让您的大语言模型项目如虎添翼
> 
> 欢迎来到您的AI助手中心,这里是您优化大语言模型(LLM)性能的一站式平台。我们精心打造的工具和资源将帮助您突破AI极限,实现更智能、更高效的项目部署。
> 
> 我们的GPU内存计算器为您提供精确估算,确保资源得到最佳分配,避免浪费。个性化的模型推荐功能则根据您的硬件配置、项目需求和性能目标,为您量身定制最佳LLM选择。
> 
> 但这仅仅是开始。我们不断更新的知识库汇集了LLM优化技巧、最佳实践和行业洞察,让您始终站在AI创新的前沿。无论您是刚刚起步还是经验丰富的开发者,这里都有助您登峰造极的宝贵资源。
> 
> 准备好释放AI的全部潜力了吗?立即加入我们,让您的LLM项目腾飞!

可以提供一个网站icon的链接吗？解析不出来

**Comment by zhushen12580** [comment]
图标是base64的，我明天发您https://llmgpuhelper.com/static/pic/logo4.png

**Comment by iAmCorey** [comment]
> 图标是base64的，我明天发您https://llmgpuhelper.com/static/pic/logo4.png

好的，是网站favicon那个图的链接，不是Logo的这种

**Comment by zhushen12580** [comment]
早，是下面这个链接
https://llmgpuhelper.com/static/pic/logo2.ico

**Comment by iAmCorey** [comment]
> 早，是下面这个链接 https://llmgpuhelper.com/static/pic/logo2.ico

已收录在Infrastructure类目下
